# Generated by Django 4.2.6 on 2024-12-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Date and Time')),
                ('aqi', models.FloatField(verbose_name='Air Quality Index (AQI)')),
                ('co', models.FloatField(verbose_name='Carbon Monoxide (CO)')),
                ('no', models.FloatField(verbose_name='Nitric Oxide (NO)')),
                ('no2', models.FloatField(verbose_name='Nitrogen Dioxide (NO2)')),
                ('o3', models.FloatField(verbose_name='Ozone (O3)')),
                ('so2', models.FloatField(verbose_name='Sulfur Dioxide (SO2)')),
                ('pm2_5', models.FloatField(verbose_name='Particulate Matter (PM2.5)')),
                ('pm10', models.FloatField(verbose_name='Particulate Matter (PM10)')),
                ('nh3', models.FloatField(verbose_name='Ammonia (NH3)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_data', to='mysite.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Air Quality Record',
                'verbose_name_plural': 'Air Quality Records',
            },
        ),
    ]
